<% ' ------------------ 快速連結 選單  ---------------------%>

          <option value=" ">其它連結</option>
          <option value="http://www.im.isu.edu.tw/project/iemweb/首頁之主.htm">返回首頁
          <option value="http://www.im.isu.edu.tw/project/iemweb/學員專區之主.htm">學員專區
          <option value="http://www.im.isu.edu.tw/project/iemweb/課程內容之主.htm">課程內容
          <option value="http://www.im.isu.edu.tw/project/iemweb/相關網站之主.htm">相關網站
          <option value="http://www.im.isu.edu.tw/project/iemweb/download/download.asp">下載區
          <option value="http://www.im.isu.edu.tw/project/iemweb/news/news.asp">最新消息
          <option value="http://www.im.isu.edu.tw/project/iemweb/guestbook/book.asp">留言板
          <option value="http://www.im.isu.edu.tw/project/iemweb/board/board.asp">討論區
          <option value="http://www.im.isu.edu.tw/project/iemweb/個人網頁之主.htm">個人網頁